###
POST https://testvm1.rokt.io/api/jsonql HTTP/1.1
Content-Type: application/json
x-api-key: c37861c7-7414-4a40-bbd8-3343662e4483

{
    "authLogin": {
		"email": "js+dev8@rokt.io",
		"pass": "Helloworld"
	}
}